version: '3'

services:     
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - laravel_pub:/var/www/html/public
      - laravel_app:/var/www/html/
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=xvq3301
      - TZ=UTC
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: laravel-nginx
    restart: on-failure
    volumes:
      - laravel_app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=xvq3301
      - TZ=UTC

volumes:
  dbdata:
  laravel_pub:
  laravel_app:

networks:
  app-network:
    driver: bridge
